### PR TITLE
Density plot with averages by gender

### PR DESCRIPTION
**Pull request by MRuzzante**
**Kernel density plots of an outcome variable over treatment group and gender with average line and text box.**

The color palette used is inspired by the Telegraph, which, in turn, was "inspired by the 'Votes for Women' campaign in the UK as part of the initial suffrage movement in the early 20th century".

See https://blog.datawrapper.de/gendercolor/#fn1 for a discussion on colors and gender data and https://www.telegraph.co.uk/women/business/women-mean-business-interactive/ for the Telegraph case (h/t @luizaandrade).

### CODE REVIEW

**Comment by luizaandrade** [comment]
Thanks, Matteo! I'll put it up next week when I'm back to the office.

**Comment by MRuzzante** [comment]
No worries, Luiza! I will also add more graphs in the next days.

I did not include any tag, but I guess you can use the ones, which already exist, such as `stata`, `graph`, `plots`, `impact-evaluations`, and perhaps also `density`, `average`, `gender`, `text-box`.

**Comment by luizaandrade** [comment]
Thanks! The description is actually great, and the search should work on it.

**Comment by MRuzzante** [comment]
I actually ended up committing two new graphs in the same pull request:

1. **Quantile treatment effect estimates with fixed effects and clustered standard errors using `qreg` and `coefplot`**
2. **Quantile treatment effect estimates by gender with fixed effects and clustered standard errors using `qreg` and `coefplot`**

You could use as tags: `stata`, `graph`, `plots`, `impact-evaluations`, `quantile-regression`, `coefplot`, and `gender` (only for the second one). Perhaps, it also makes sense to make a folder only for quantile regressions and impact distributional analysis, instead of keeping it under "Regression coefficients". Your choice! ;)

For useful resources/links, you could attach this paper by Lupe to the graph comment: http://documents.worldbank.org/curated/en/292901499351272899/Distributional-impact-analysis-toolkit-and-illustrations-of-impacts-beyond-the-average-treatment-effect

**Pull request merged**
